version: "3.8"

services:
    dbtest:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: symfony_test
            POSTGRES_USER: symfony_test
            POSTGRES_PASSWORD: symfony_test
        ports:
            - "5433:5432"
        networks:
            - test

    phptest:
        image: rafiousitou/sf5-php-8.0:dev
        volumes:
            - ./:/var/www/app:rw,cached
        depends_on:
            - dbtest
        networks:
            - test

networks:
    test: